# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janreinberg/max-sdk/source/audio/simplemsp~/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janreinberg/max-sdk/source/max-sdk-base/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/janreinberg/max-sdk/source/max-sdk-base/script/max-pretarget.cmake))

/Users/janreinberg/max-sdk/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -S/Users/janreinberg/max-sdk -B/Users/janreinberg/max-sdk/build
